spring:
  application:
    name: PropertyManager
  datasource:
    url: jdbc:postgresql://localhost:5432/propertymanager
    username: ${SQL_USERNAME}
    password: ${SQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
